language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3

env:
    allow_failures:
        - python: 3.5
    matrix:
        - DJANGO_VERSION=1.6.11
        - DJANGO_VERSION=1.7.8
        - DJANGO_VERSION=1.8.2

install:
    - pip install -q Django==$DJANGO_VERSION
    - python setup.py -q install
    - python setup.py test
    - pip install coveralls

script:
    - py.test
    - coverage run --source=coveralls py.test
    - coverage report -m

after_script:
    coveralls --verbose

notifications:
    email:
        - alainivars@gmail.com
