language: python

python:
    - "2.7"
    - "3.4"
    # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
    # maintainers to fix their pypy-dev package.
    #- "pypy"

env:
    matrix:
        - DJANGO_VERSION=1.6.11
        - DJANGO_VERSION=1.7.8
        - DJANGO_VERSION=1.8.2

# command to install dependencies
install:
    - pip install -q Django==$DJANGO_VERSION
    - python setup.py -q install
    - python setup.py test
    - pip install coveralls

script:
   - py.test
#  - python setup.py test_on_travis
#  - nosetests --with-coverage --cover-package=sentry
#  - flake8 .
#  - "if [[ ${TRAVIS_PYTHON_VERSION} != 'pypy' ]]; then make lint; fi"
#  - py.test tests/ --cov raven --cov-report term-missing

notifications:
    email:
        - alainivars@gmail.com
